/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsDataScienceAiRouteImport } from './routes/programs.data-science-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsDataScienceAiRoute = ProgramsDataScienceAiRouteImport.update({
  id: '/programs/data-science-ai',
  path: '/programs/data-science-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programs/data-science-ai': typeof ProgramsDataScienceAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programs/data-science-ai': typeof ProgramsDataScienceAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/programs/data-science-ai': typeof ProgramsDataScienceAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programs/data-science-ai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programs/data-science-ai'
  id: '__root__' | '/' | '/programs/data-science-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramsDataScienceAiRoute: typeof ProgramsDataScienceAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/data-science-ai': {
      id: '/programs/data-science-ai'
      path: '/programs/data-science-ai'
      fullPath: '/programs/data-science-ai'
      preLoaderRoute: typeof ProgramsDataScienceAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramsDataScienceAiRoute: ProgramsDataScienceAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
