/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ServicesNowGeneralistRouteImport } from './routes/servicesNowGeneralist'
import { Route as ServicesNowDevelopersRouteImport } from './routes/servicesNowDevelopers'
import { Route as ServicesNowRouteImport } from './routes/services-now'
import { Route as ReturnAndRefundPolicyRouteImport } from './routes/return-and-refund-policy'
import { Route as ReferAndEarnRouteImport } from './routes/refer-and-earn'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlacementStoriesRouteImport } from './routes/placement-stories'
import { Route as HelpRouteImport } from './routes/help'
import { Route as Datascience_OJTRouteImport } from './routes/datascience_OJT'
import { Route as DataScienceGeneralistRouteImport } from './routes/dataScienceGeneralist'
import { Route as DataScienceDevelopersRouteImport } from './routes/dataScienceDevelopers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AgenticGeneralistRouteImport } from './routes/agenticGeneralist'
import { Route as AgenticDevelopersRouteImport } from './routes/agenticDevelopers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Internship_for_Full_Stack_DevelopersRouteImport } from './routes/Internship_for_Full_Stack_Developers'
import { Route as Internship_for_Data_ScientistsRouteImport } from './routes/Internship_for_Data_Scientists'
import { Route as Datascience_CertificationRouteImport } from './routes/Datascience_Certification'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as ProgramsDataScienceAiRouteImport } from './routes/programs.data-science-ai'
import { Route as BlogsTopicRouteImport } from './routes/blogs.$topic'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNowGeneralistRoute = ServicesNowGeneralistRouteImport.update({
  id: '/servicesNowGeneralist',
  path: '/servicesNowGeneralist',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNowDevelopersRoute = ServicesNowDevelopersRouteImport.update({
  id: '/servicesNowDevelopers',
  path: '/servicesNowDevelopers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNowRoute = ServicesNowRouteImport.update({
  id: '/services-now',
  path: '/services-now',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnAndRefundPolicyRoute = ReturnAndRefundPolicyRouteImport.update({
  id: '/return-and-refund-policy',
  path: '/return-and-refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferAndEarnRoute = ReferAndEarnRouteImport.update({
  id: '/refer-and-earn',
  path: '/refer-and-earn',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementStoriesRoute = PlacementStoriesRouteImport.update({
  id: '/placement-stories',
  path: '/placement-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const Datascience_OJTRoute = Datascience_OJTRouteImport.update({
  id: '/datascience_OJT',
  path: '/datascience_OJT',
  getParentRoute: () => rootRouteImport,
} as any)
const DataScienceGeneralistRoute = DataScienceGeneralistRouteImport.update({
  id: '/dataScienceGeneralist',
  path: '/dataScienceGeneralist',
  getParentRoute: () => rootRouteImport,
} as any)
const DataScienceDevelopersRoute = DataScienceDevelopersRouteImport.update({
  id: '/dataScienceDevelopers',
  path: '/dataScienceDevelopers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticGeneralistRoute = AgenticGeneralistRouteImport.update({
  id: '/agenticGeneralist',
  path: '/agenticGeneralist',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticDevelopersRoute = AgenticDevelopersRouteImport.update({
  id: '/agenticDevelopers',
  path: '/agenticDevelopers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Internship_for_Full_Stack_DevelopersRoute =
  Internship_for_Full_Stack_DevelopersRouteImport.update({
    id: '/Internship_for_Full_Stack_Developers',
    path: '/Internship_for_Full_Stack_Developers',
    getParentRoute: () => rootRouteImport,
  } as any)
const Internship_for_Data_ScientistsRoute =
  Internship_for_Data_ScientistsRouteImport.update({
    id: '/Internship_for_Data_Scientists',
    path: '/Internship_for_Data_Scientists',
    getParentRoute: () => rootRouteImport,
  } as any)
const Datascience_CertificationRoute =
  Datascience_CertificationRouteImport.update({
    id: '/Datascience_Certification',
    path: '/Datascience_Certification',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const ProgramsDataScienceAiRoute = ProgramsDataScienceAiRouteImport.update({
  id: '/programs/data-science-ai',
  path: '/programs/data-science-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsTopicRoute = BlogsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Datascience_Certification': typeof Datascience_CertificationRoute
  '/Internship_for_Data_Scientists': typeof Internship_for_Data_ScientistsRoute
  '/Internship_for_Full_Stack_Developers': typeof Internship_for_Full_Stack_DevelopersRoute
  '/about': typeof AboutRoute
  '/agenticDevelopers': typeof AgenticDevelopersRoute
  '/agenticGeneralist': typeof AgenticGeneralistRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dataScienceDevelopers': typeof DataScienceDevelopersRoute
  '/dataScienceGeneralist': typeof DataScienceGeneralistRoute
  '/datascience_OJT': typeof Datascience_OJTRoute
  '/help': typeof HelpRoute
  '/placement-stories': typeof PlacementStoriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refer-and-earn': typeof ReferAndEarnRoute
  '/return-and-refund-policy': typeof ReturnAndRefundPolicyRoute
  '/services-now': typeof ServicesNowRoute
  '/servicesNowDevelopers': typeof ServicesNowDevelopersRoute
  '/servicesNowGeneralist': typeof ServicesNowGeneralistRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blogs/$topic': typeof BlogsTopicRoute
  '/programs/data-science-ai': typeof ProgramsDataScienceAiRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Datascience_Certification': typeof Datascience_CertificationRoute
  '/Internship_for_Data_Scientists': typeof Internship_for_Data_ScientistsRoute
  '/Internship_for_Full_Stack_Developers': typeof Internship_for_Full_Stack_DevelopersRoute
  '/about': typeof AboutRoute
  '/agenticDevelopers': typeof AgenticDevelopersRoute
  '/agenticGeneralist': typeof AgenticGeneralistRoute
  '/contact': typeof ContactRoute
  '/dataScienceDevelopers': typeof DataScienceDevelopersRoute
  '/dataScienceGeneralist': typeof DataScienceGeneralistRoute
  '/datascience_OJT': typeof Datascience_OJTRoute
  '/help': typeof HelpRoute
  '/placement-stories': typeof PlacementStoriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refer-and-earn': typeof ReferAndEarnRoute
  '/return-and-refund-policy': typeof ReturnAndRefundPolicyRoute
  '/services-now': typeof ServicesNowRoute
  '/servicesNowDevelopers': typeof ServicesNowDevelopersRoute
  '/servicesNowGeneralist': typeof ServicesNowGeneralistRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blogs/$topic': typeof BlogsTopicRoute
  '/programs/data-science-ai': typeof ProgramsDataScienceAiRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Datascience_Certification': typeof Datascience_CertificationRoute
  '/Internship_for_Data_Scientists': typeof Internship_for_Data_ScientistsRoute
  '/Internship_for_Full_Stack_Developers': typeof Internship_for_Full_Stack_DevelopersRoute
  '/about': typeof AboutRoute
  '/agenticDevelopers': typeof AgenticDevelopersRoute
  '/agenticGeneralist': typeof AgenticGeneralistRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dataScienceDevelopers': typeof DataScienceDevelopersRoute
  '/dataScienceGeneralist': typeof DataScienceGeneralistRoute
  '/datascience_OJT': typeof Datascience_OJTRoute
  '/help': typeof HelpRoute
  '/placement-stories': typeof PlacementStoriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refer-and-earn': typeof ReferAndEarnRoute
  '/return-and-refund-policy': typeof ReturnAndRefundPolicyRoute
  '/services-now': typeof ServicesNowRoute
  '/servicesNowDevelopers': typeof ServicesNowDevelopersRoute
  '/servicesNowGeneralist': typeof ServicesNowGeneralistRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blogs/$topic': typeof BlogsTopicRoute
  '/programs/data-science-ai': typeof ProgramsDataScienceAiRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Datascience_Certification'
    | '/Internship_for_Data_Scientists'
    | '/Internship_for_Full_Stack_Developers'
    | '/about'
    | '/agenticDevelopers'
    | '/agenticGeneralist'
    | '/blogs'
    | '/contact'
    | '/dataScienceDevelopers'
    | '/dataScienceGeneralist'
    | '/datascience_OJT'
    | '/help'
    | '/placement-stories'
    | '/privacy-policy'
    | '/refer-and-earn'
    | '/return-and-refund-policy'
    | '/services-now'
    | '/servicesNowDevelopers'
    | '/servicesNowGeneralist'
    | '/terms-and-conditions'
    | '/blogs/$topic'
    | '/programs/data-science-ai'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Datascience_Certification'
    | '/Internship_for_Data_Scientists'
    | '/Internship_for_Full_Stack_Developers'
    | '/about'
    | '/agenticDevelopers'
    | '/agenticGeneralist'
    | '/contact'
    | '/dataScienceDevelopers'
    | '/dataScienceGeneralist'
    | '/datascience_OJT'
    | '/help'
    | '/placement-stories'
    | '/privacy-policy'
    | '/refer-and-earn'
    | '/return-and-refund-policy'
    | '/services-now'
    | '/servicesNowDevelopers'
    | '/servicesNowGeneralist'
    | '/terms-and-conditions'
    | '/blogs/$topic'
    | '/programs/data-science-ai'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/Datascience_Certification'
    | '/Internship_for_Data_Scientists'
    | '/Internship_for_Full_Stack_Developers'
    | '/about'
    | '/agenticDevelopers'
    | '/agenticGeneralist'
    | '/blogs'
    | '/contact'
    | '/dataScienceDevelopers'
    | '/dataScienceGeneralist'
    | '/datascience_OJT'
    | '/help'
    | '/placement-stories'
    | '/privacy-policy'
    | '/refer-and-earn'
    | '/return-and-refund-policy'
    | '/services-now'
    | '/servicesNowDevelopers'
    | '/servicesNowGeneralist'
    | '/terms-and-conditions'
    | '/blogs/$topic'
    | '/programs/data-science-ai'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Datascience_CertificationRoute: typeof Datascience_CertificationRoute
  Internship_for_Data_ScientistsRoute: typeof Internship_for_Data_ScientistsRoute
  Internship_for_Full_Stack_DevelopersRoute: typeof Internship_for_Full_Stack_DevelopersRoute
  AboutRoute: typeof AboutRoute
  AgenticDevelopersRoute: typeof AgenticDevelopersRoute
  AgenticGeneralistRoute: typeof AgenticGeneralistRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DataScienceDevelopersRoute: typeof DataScienceDevelopersRoute
  DataScienceGeneralistRoute: typeof DataScienceGeneralistRoute
  Datascience_OJTRoute: typeof Datascience_OJTRoute
  HelpRoute: typeof HelpRoute
  PlacementStoriesRoute: typeof PlacementStoriesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReferAndEarnRoute: typeof ReferAndEarnRoute
  ReturnAndRefundPolicyRoute: typeof ReturnAndRefundPolicyRoute
  ServicesNowRoute: typeof ServicesNowRoute
  ServicesNowDevelopersRoute: typeof ServicesNowDevelopersRoute
  ServicesNowGeneralistRoute: typeof ServicesNowGeneralistRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ProgramsDataScienceAiRoute: typeof ProgramsDataScienceAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicesNowGeneralist': {
      id: '/servicesNowGeneralist'
      path: '/servicesNowGeneralist'
      fullPath: '/servicesNowGeneralist'
      preLoaderRoute: typeof ServicesNowGeneralistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicesNowDevelopers': {
      id: '/servicesNowDevelopers'
      path: '/servicesNowDevelopers'
      fullPath: '/servicesNowDevelopers'
      preLoaderRoute: typeof ServicesNowDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-now': {
      id: '/services-now'
      path: '/services-now'
      fullPath: '/services-now'
      preLoaderRoute: typeof ServicesNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-and-refund-policy': {
      id: '/return-and-refund-policy'
      path: '/return-and-refund-policy'
      fullPath: '/return-and-refund-policy'
      preLoaderRoute: typeof ReturnAndRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer-and-earn': {
      id: '/refer-and-earn'
      path: '/refer-and-earn'
      fullPath: '/refer-and-earn'
      preLoaderRoute: typeof ReferAndEarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-stories': {
      id: '/placement-stories'
      path: '/placement-stories'
      fullPath: '/placement-stories'
      preLoaderRoute: typeof PlacementStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datascience_OJT': {
      id: '/datascience_OJT'
      path: '/datascience_OJT'
      fullPath: '/datascience_OJT'
      preLoaderRoute: typeof Datascience_OJTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataScienceGeneralist': {
      id: '/dataScienceGeneralist'
      path: '/dataScienceGeneralist'
      fullPath: '/dataScienceGeneralist'
      preLoaderRoute: typeof DataScienceGeneralistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataScienceDevelopers': {
      id: '/dataScienceDevelopers'
      path: '/dataScienceDevelopers'
      fullPath: '/dataScienceDevelopers'
      preLoaderRoute: typeof DataScienceDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenticGeneralist': {
      id: '/agenticGeneralist'
      path: '/agenticGeneralist'
      fullPath: '/agenticGeneralist'
      preLoaderRoute: typeof AgenticGeneralistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenticDevelopers': {
      id: '/agenticDevelopers'
      path: '/agenticDevelopers'
      fullPath: '/agenticDevelopers'
      preLoaderRoute: typeof AgenticDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Internship_for_Full_Stack_Developers': {
      id: '/Internship_for_Full_Stack_Developers'
      path: '/Internship_for_Full_Stack_Developers'
      fullPath: '/Internship_for_Full_Stack_Developers'
      preLoaderRoute: typeof Internship_for_Full_Stack_DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Internship_for_Data_Scientists': {
      id: '/Internship_for_Data_Scientists'
      path: '/Internship_for_Data_Scientists'
      fullPath: '/Internship_for_Data_Scientists'
      preLoaderRoute: typeof Internship_for_Data_ScientistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Datascience_Certification': {
      id: '/Datascience_Certification'
      path: '/Datascience_Certification'
      fullPath: '/Datascience_Certification'
      preLoaderRoute: typeof Datascience_CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/programs/data-science-ai': {
      id: '/programs/data-science-ai'
      path: '/programs/data-science-ai'
      fullPath: '/programs/data-science-ai'
      preLoaderRoute: typeof ProgramsDataScienceAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$topic': {
      id: '/blogs/$topic'
      path: '/$topic'
      fullPath: '/blogs/$topic'
      preLoaderRoute: typeof BlogsTopicRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsTopicRoute: typeof BlogsTopicRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsTopicRoute: BlogsTopicRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Datascience_CertificationRoute: Datascience_CertificationRoute,
  Internship_for_Data_ScientistsRoute: Internship_for_Data_ScientistsRoute,
  Internship_for_Full_Stack_DevelopersRoute:
    Internship_for_Full_Stack_DevelopersRoute,
  AboutRoute: AboutRoute,
  AgenticDevelopersRoute: AgenticDevelopersRoute,
  AgenticGeneralistRoute: AgenticGeneralistRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ContactRoute: ContactRoute,
  DataScienceDevelopersRoute: DataScienceDevelopersRoute,
  DataScienceGeneralistRoute: DataScienceGeneralistRoute,
  Datascience_OJTRoute: Datascience_OJTRoute,
  HelpRoute: HelpRoute,
  PlacementStoriesRoute: PlacementStoriesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReferAndEarnRoute: ReferAndEarnRoute,
  ReturnAndRefundPolicyRoute: ReturnAndRefundPolicyRoute,
  ServicesNowRoute: ServicesNowRoute,
  ServicesNowDevelopersRoute: ServicesNowDevelopersRoute,
  ServicesNowGeneralistRoute: ServicesNowGeneralistRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ProgramsDataScienceAiRoute: ProgramsDataScienceAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
